# Generated by Django 2.0.2 on 2018-03-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'permissions': (('can_delete', 'Story can be deleted.'), ('can_add', 'Story can be added.'))},
        ),
    ]
