# Generated by Django 2.0.2 on 2018-03-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0003_renamed_People_model_to_Post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('votes',)},
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
