# Generated by Django 2.0.2 on 2018-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0004_add_manager_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting_manager',
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
