# Generated by Django 2.0.2 on 2018-03-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0006_add_django_vote_app_for_voting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
