# Generated by Django 2.0.2 on 2018-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0007_auto_20180322_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('votes',)},
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
