# Generated by Django 2.0.2 on 2018-03-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0008_auto_20180322_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('votings',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='votes',
            new_name='votings',
        ),
    ]
