# Generated by Django 2.0.2 on 2018-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0009_auto_20180322_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-votings',)},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='foo', max_length=30),
        ),
    ]
