# Generated by Django 2.0.2 on 2018-05-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsitapp', '0010_ame=add_author_field_in_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='first_name',
        ),
    ]
